### ISSUE TITLE
print $DIR/sowh_trace_$name.txt with output similar to phylobayes .trace files

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#11]
eg

  #cycle  #treegen        time    loglik  length  alpha   nmode   stat
  1       940     2836    -889000 21.9549 0.585788        4885    0.933128

**Comment by shchurch** [comment]
Trace file now printed to sowhat.trace.txt in [--dir]. The trace file includes the following:
time(s)	sample_size	low_conf_int	p_value	high_conf_int
separated by tabs
