### ISSUE TITLE
raxml returns higher likelihood for constrained tree than unconstrained tree for some simulated matrices

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#13]
This is a known issue, and is addressed here:

https://groups.google.com/forum/#!topic/raxml/qn7_ZXoJTHg

We should redo some of hte problematic searches with the addition of the `--no-bfgs` raxml option. If that fixes the problem for those matrices, we should rerun the tests in the manuscript that were impacted by this. If they work, we should revise the manuscript to reflect the fix.

**Comment by shchurch** [comment]
Currently testing if removing BFGS protocol resolves the issue. Preliminary results indicate that yes. See https://groups.google.com/forum/#!topic/raxml/qn7_ZXoJTHg

**Comment by caseywdunn** [comment]
RAxML restored to default lieklihood engine.
