### ISSUE TITLE
seq-gen has limited model set. sowhat needs to check models before any processes are run.

### ISSUE THREAD

**Issue by josephryan** [josephryan/sowhat#20]

**Comment by shchurch** [comment]
Model checks were integrated previously. The available models are listed below. Specifying any other models should return this error at the outset.
sowhat recognizes the following models:
    nucleotide data:
        - RAxML models - GTRGAMMA[I|X] GTRCAT[I|X] 
          (CAT model will not be used for simulation)
        - GARLI models - all options except fixed
    amino acid data:
        - RAxML models - PROTGAMMA[I|X]... PROTCAT[I|X]  
          (CAT model will not be used for simulation)
          matrices: JTT WAG DAYHOFF BLOSUM62 MTREV CPREV45 GTR GTR_UNLINKED
        - GARLI models - all options except fixed
          matrices: JONES WAG DAYHOFF MTREV MTMAM
    character data:
        - RAxML models - MULTIGAMMA[I|X] MULTICAT[I|X]  
          anywhere from 2 - 20 character states are supported
          characters must be used in this order as they are available
              0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J  
          these will be resorted from most to least freq. in simulations
          many low frequency character states will return a raxml error
          (CAT model will not be used for simulation)
        - GARLI + character data is currently not available
    alternative options:
        - The PhyloBayes CAT_GTR model can be used for parameter 
          estimation and data simulation w/ --usepb
        - A user specified model can be used for simulation w/ --usegenmodel 
          see example file examples/simulation.model
        - The user can specify the --max option to maximize free 
          parameters used in simulation
