### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#23]
At present the output is simple text. This makes it difficult for it to be machine readable since text format may change in unspecified ways from version to version, and therefor for SOWHAT to be wrapped into larger workflows.

We should generate structured output as a json file. This should then be read and formatted as a text output, similar to what we have now. It could also be parsed into an easy-to-read html output.

**Comment by shchurch** [comment]
output can be printed to a json file using the --json option.
