### ISSUE TITLE
instructions for monitoring a job - and cutting a job short

### ISSUE THREAD

**Issue by josephryan** [josephryan/sowhat#24]
SOWH tests can take a long time on large datasets. Here are some ideas on how to monitor a job and how to cut a job short.  These should be considered (and tested) for being added to the documentation:
1. Monitoring a  job
   the following command can be used to monitor a job (only if reps = 1 - the default) if run from within the directory that was specified with the --dir option:
   
   <pre>ls -1 sowhat_scratch/ | cut -f 4 -d '.' | sort -n | tail -n1</pre>
2. Cutting a job short
   If the job is currently running, make a copy of the directory that was specified with the --dir option (and its contents) :
   
   <pre>cp -R myoutputdir rerunoutputdir</pre>
   
   run the exact same command as before, but with this new directory as the --dir option, and 
   
   <pre>--reps=SMALLER_NUMBER_OF_REPS --restart</pre>

**Comment by shchurch** [comment]
The documentation in the README has been updated to reflect the following:
1. The most informative way to monitor a job is to check the contents of the file [--dir]/sowhat.results.txt. This file contains the sample size and the current p-value, and is updated after each new sample is added to the null distribution.
2. A run that has been cut short can be restarted using the --restart option. In this case the null distribution will be recalculated iteratively using the previously simulated samples in the null distributions. Only the most recent two generations of sequence simulation and tree estimation will be reperformed to prevent any errors from an unfinished tree estimation.
