### ISSUE TITLE
sowhat should throw error if reps < 10

### ISSUE THREAD

**Issue by josephryan** [josephryan/sowhat#26]
"The problem with these arguments is that you have set the maximum number of reps to 2 (--reps=2) - this means that sowhat will generate only two simulated datasets and this is not enough to calculate any statistics, such as a p-value. sowhat won't start printing a sowhat.results.txt file until after the 10th bootstrap replicate to avoid choking on any mathematical errors near the start of the analysis. We strongly recommend each analysis should use 100+ bootstrap replicates, and that the number of bootstraps (the sample size) should be justified by reporting the confidence interval surrounding the p-value"

**Comment by shchurch** [comment]
Error now thrown.
