### ISSUE TITLE
Failing travis ci due to old R

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#31]
The TravisCI test is failing: https://travis-ci.org/josephryan/sowhat/builds/221453597

The problem seems to be:
- The test images is based on Ubuntu 14.04.5 LTS
- `sudo apt-get install -y r-base` installs R 3.0.2
- The `ape` package is unavailable for this older R, throwing the warning `package 'ape' is not available (for R version 3.0.2) `
- Results in the error `library(ape) : there is no package called 'ape'`

We should figure out how to install a more recent version of R on this container or use a different test image that allows installation of newer R.

**Comment by caseywdunn** [comment]
I migrated from vm to container build with `sudo:false`, but that now breaks installation of apt resources since don't have permission to run `apt-get update`. https://travis-ci.org/josephryan/sowhat/builds/230746216

Instead of making explicit `apt-get` calls, need to modify as described here:

https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F

**Comment by shchurch** [comment]
Hey Casey,

Thanks for looking at this! I am out of town through the weekend so I won't
be able to support right now, but will take a look first thing next week.
Sorry for the timing!

Sam

**Comment by caseywdunn** [comment]
No problem Sam!

I managed to figure out how to use a more recent version of R to fix the ape problem, but that in turn broke `cpanm`. https://travis-ci.org/josephryan/sowhat/builds/230847664

I'll leave it there for now...

**Comment by shchurch** [comment]
merged branch issue-31 into development. Travis-ci now building correctly. Added a line to sowhat code where it calls R to search an additional lib path called ~/R_travis_lib. Travis ci config file installs R libraries there.
