### ISSUE TITLE
Allow for comparison of two suboptimal hypotheses

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#6]
Right now limited to most likely topology vs. a single alternative.

**Comment by shchurch** [comment]
this can be done with the --treetwo option
           This allows a user to specify a second tree against which to
           compare the null hypothesis. The two trees (constraint and treetwo)
           will be compared. The lower likelihood tree will be used as the
           constraining hypothesis for parameter estimation and simulation.
