### ISSUE TITLE
Add support for threads (multiCPU)

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#7]

**Comment by shchurch** [comment]
Maybe try perl threads for this, or at a minimum implement the pause and run multithread raxml method suggested by a user.

**Comment by shchurch** [comment]
For datasets where the tree searches can take many hours, sowhat can be very slow. To incorporate parallelization, the user has two options. First, the user can specify a threaded version of raxml with the --rax option (see documentation). Second, with v0.39, the user can execute the tree searches on the simulated alignments externally using the --print_tree_scripts option. Please see the added documentation on the README for more information on this option.
