### ISSUE TITLE
Add true support for multistate

### ISSUE THREAD

**Issue by caseywdunn** [josephryan/sowhat#8]
Will require running seq-gen in aminoacid mode and up to 20 substitutions. multistate currently fails with: "expecting 2 frequencies. Multi-State only works w/binary matrix".

**Comment by shchurch** [comment]
sowhat now supports up to 20 state characters with raxml. Model options are as follows:
    character data:
        - RAxML models - MULTIGAMMA[I|X] MULTICAT[I|X]  
          anywhere from 2 - 20 character states are supported
          characters must be used in this order as they are available
              0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J  
          these will be resorted from most to least freq. in simulations
          many low frequency character states will return a raxml error
          (CAT model will not be used for simulation)
